schema = 3

[mod]
  [mod."github.com/gertd/go-pluralize"]
    version = "v0.2.1"
    hash = "sha256-raTQUWJXcFZwCHNQnj2AhVPf8bRzLrfjp5Dp7dVZLtU="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/hashicorp/cronexpr"]
    version = "v1.1.2"
    hash = "sha256-V3nG6IFjb3Jx0eU5KwklcHo7ML3K6F8J2uAZmIvvXsc="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.0.0"
    hash = "sha256-LGSLrefkABG1kH1i+GUWiD2/ggJxiZEJ+D2YNbhZjmo="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/go-rootcerts"]
    version = "v1.0.2"
    hash = "sha256-prifkrFs+lawGTig3GwxddR0QM9E1+IpgZWCKoOnS5M="
  [mod."github.com/hashicorp/nomad/api"]
    version = "v0.0.0-20240403130644-e7b25a25014a"
    hash = "sha256-At4ZTEyzBCFNC/TlqjInaOHQN9Yac7PHdGSTM3r84bg="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.0"
    hash = "sha256-X0ilcefeqVQ44B9WT6euCMcigs7oLFypOQaGI33kGr8="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230728194245-b0cb94b80691"
    hash = "sha256-jqh9fxEEsuDzG7Gj/3Is3EmMKJf26RHovBte2LFh2Bw="
